### ISSUE TITLE
Define

### ISSUE THREAD

**Issue by vanh17** [vanh17/SnoopCH#22]
Dear Dr. @skiadas 
So I think we actually have to put the bind into the empty environment for the binding so that it will now become the global environment. Is that correct?
Warmest.
Hoang

**Comment by skiadas** [comment]
Ah ok so there�s many things a �define� does. The first is that it establishes bindings for future statements. For that all you need to do is update your environment in your evaluate, instead of always starting from the empty one. That�s reasonably doable, using a reference to store the environment in-between evaluates.

The second thing that define does is that it allows your binding to refer to itself. That is harder to do. Basically you need to have an env, that in it has a binding for say the function f. That function then is computed and that environment env is stored in its closure. Then in _that same env_ we need to _change_ the binding of f to be that closure. The only way to do that is via mutation, and in ocaml that means refs. So you need to create a new �value� that is a ref to an option value (value option ref), and that represents a �delayed binding�. You will need to change a bit your code that does lookup in the environment, as it now needs to dig into that ref option and return the value there, or return an error if that option is None (represents trying to access an uninitialized value). You then create a reference r = ref None, and bind f to it and put that in the environment in which you evaluate f. After the evaluation, you change the reference to now contain Some cl where cl is the closure you just evaluated. This will actually change the binding for f in the environment that is stored with it.
Yep, tricky stuff.

The third thing that define does is that it allows you to refer to bindings created by future defines. There�s no way to really implement that in your current setup. You need the idea of loading a whole file, rather than evaluating line by line.

**Comment by vanh17** [comment]
So I think I get the error :"opeartion expected" in lookup function. I was wondering if you could have a look on this and help me out please. Thank you so much Dr. @skiadas Skiadas

**Comment by vanh17** [comment]
I think the right question should how we can actually know a variable is a ref or just a normal value. Can we use match some how to determine it?
In my code I used match v with
                             | ref _ -> do something here....

**Comment by skiadas** [comment]
Yes you should do a match on the value. But "ref" is not an option, "RefToOpV r" would be, where r is a ref. that you can then look at its content and then pattern match on whether that's a Some or None.
